

services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8081:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - astro-project_974df4_airflow
  # Nessie Catalog Server Using In-Memory Store
  nessie-server:
    image: ghcr.io/projectnessie/nessie
    networks:
      - astro-project_974df4_airflow
    ports:
      - 19120:19120
  # Minio Storage Server
  minio-server:
    image: 'minio/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      - astro-project_974df4_airflow
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  mysql:
    image: debezium/example-mysql:2.5
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - astro-project_974df4_airflow
networks:
  astro-project_974df4_airflow:
    external: true